# Generated by Django 5.1.5 on 2025-01-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tags',
        ),
    ]
