# Generated by Django 5.1.5 on 2025-01-25 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_comment_parent_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_username',
            field=models.TextField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
